types/seat: Clear focus in wlr_seat_destroy()
swaywm/wlroots pull request #2582
Opened 2020-12-28 15:14 UTC by any1

This fixes use-after-free in surface destroy signal listeners.

2021-01-01 18:01 UTC, emersion commented
I think this makes sense. We do something similar for unmap signals for xdg-shell, by guaranteeing that unmap is always triggered before destroy.

2021-01-06 13:47 UTC, emersion requested changes
Can we also document this guarantee in the header?

2021-01-06 13:47 UTC, emersion commented on types/seat/wlr_seat.c
> +	struct wlr_touch_point* point;
Style: `*` on the right

2021-01-06 22:11 UTC, any1 commented on types/seat/wlr_seat.c
> +	struct wlr_touch_point* point;
Done.

2021-01-07 13:35 UTC, emersion approved these changes
LGTM, thanks!

2021-01-07 13:35 UTC, merged