Add wlr_egl_from_context
swaywm/wlroots pull request #3013
Opened 2021-07-02 02:17 UTC by technobaboo

This function (in egl.c and egl.h) is to import an external EGL context (specifically to get https://github.com/technobaboo/sk-wlroots working, but useful in many other areas). It's been tested and known to work, and does not appear to harm any of the wlroots examples.

2021-07-04 17:01 UTC, emersion requested changes

2021-07-04 17:01 UTC, emersion commented on render/egl.c
> +	if(egl == NULL)
Style: always use braces, even for single-line conditions. Applies to the whole PR.

2021-07-04 17:01 UTC, emersion commented on render/egl.c
> +	if(egl == NULL)
Style: missing space between `if` and `(`. Applies to the whole PR.

2021-07-04 22:40 UTC, technobaboo commented on render/egl.c
> +static struct wlr_egl *wlr_egl_alloc(void) {
merge `wlr_egl_alloc` with `wlr_egl_load_client_exts`? How would we output the `wlr_egl` struct and `const char *` of client extensions?

2021-07-04 22:44 UTC, technobaboo commented on render/egl.c
> +	egl->display = display;
on line 436?

2021-07-19 18:00 UTC, emersion commented on render/egl.c
> +	egl->display = display;
Basically, we should check that the context provided by the client can be used by wlroots.

- `eglQueryContext(display, context, EGL_CONTEXT_CLIENT_TYPE, &client_type)` gives `EGL_OPENGL_ES_API`
- `eglQueryContext(display, context, EGL_CONTEXT_CLIENT_VERSION, &client_version)` gives >= 2

2021-07-19 18:01 UTC, emersion commented
How will this interact with https://github.com/swaywm/wlroots/pull/2671?

2021-07-20 13:23 UTC, technobaboo commented on render/egl.c
> +	egl->display = display;
I'm actually revising it right now to make a new context that is shared to the one passed in, so this shouldn't be an issue.

2021-07-20 13:26 UTC, technobaboo commented
> How will this interact with #2671?

From what I can see it shouldn't be an issue (see https://github.com/swaywm/wlroots/pull/3013#discussion_r673118299), but I am in the middle of debugging an issue when using EGL for OpenXR and wlroots. I'll ask on the IRC channel when I get back to working on this part (focusing on other parts of my project for now).

2021-07-31 07:21 UTC, emersion commented
Needs a rebase on top of #2671.

2021-11-01 15:59 UTC, emersion commented
wlroots has migrated to gitlab.freedesktop.org. This pull request has been moved to:

https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3013

2025-03-18 19:06 UTC, closed without merging